// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyValueStoreMessage.proto

#ifndef PROTOBUF_KeyValueStoreMessage_2eproto__INCLUDED
#define PROTOBUF_KeyValueStoreMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "Address.pb.h"
// @@protoc_insertion_point(includes)
namespace gen {
class Address;
class AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class CreateRequestFields;
class CreateRequestFieldsDefaultTypeInternal;
extern CreateRequestFieldsDefaultTypeInternal _CreateRequestFields_default_instance_;
class CreateResponseFields;
class CreateResponseFieldsDefaultTypeInternal;
extern CreateResponseFieldsDefaultTypeInternal _CreateResponseFields_default_instance_;
class DeleteRequestFields;
class DeleteRequestFieldsDefaultTypeInternal;
extern DeleteRequestFieldsDefaultTypeInternal _DeleteRequestFields_default_instance_;
class DeleteResponseFields;
class DeleteResponseFieldsDefaultTypeInternal;
extern DeleteResponseFieldsDefaultTypeInternal _DeleteResponseFields_default_instance_;
class ReadRequestFields;
class ReadRequestFieldsDefaultTypeInternal;
extern ReadRequestFieldsDefaultTypeInternal _ReadRequestFields_default_instance_;
class ReadResponseFields;
class ReadResponseFieldsDefaultTypeInternal;
extern ReadResponseFieldsDefaultTypeInternal _ReadResponseFields_default_instance_;
class RequestMessage;
class RequestMessageDefaultTypeInternal;
extern RequestMessageDefaultTypeInternal _RequestMessage_default_instance_;
class ResponseMessage;
class ResponseMessageDefaultTypeInternal;
extern ResponseMessageDefaultTypeInternal _ResponseMessage_default_instance_;
class UpdateRequestFields;
class UpdateRequestFieldsDefaultTypeInternal;
extern UpdateRequestFieldsDefaultTypeInternal _UpdateRequestFields_default_instance_;
class UpdateResponseFields;
class UpdateResponseFieldsDefaultTypeInternal;
extern UpdateResponseFieldsDefaultTypeInternal _UpdateResponseFields_default_instance_;
}  // namespace gen

namespace gen {

namespace protobuf_KeyValueStoreMessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_KeyValueStoreMessage_2eproto

enum RequestMessageType {
  CREATE_REQUEST = 0,
  UPDATE_REQUEST = 1,
  READ_REQUEST = 2,
  DELETE_REQUEST = 3,
  RequestMessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RequestMessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RequestMessageType_IsValid(int value);
const RequestMessageType RequestMessageType_MIN = CREATE_REQUEST;
const RequestMessageType RequestMessageType_MAX = DELETE_REQUEST;
const int RequestMessageType_ARRAYSIZE = RequestMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RequestMessageType_descriptor();
inline const ::std::string& RequestMessageType_Name(RequestMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RequestMessageType_descriptor(), value);
}
inline bool RequestMessageType_Parse(
    const ::std::string& name, RequestMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestMessageType>(
    RequestMessageType_descriptor(), name, value);
}
enum ResponseMessageType {
  CREATE_RESPONSE = 0,
  UPDATE_RESPONSE = 1,
  READ_RESPONSE = 2,
  DELETE_RESPONSE = 3,
  ResponseMessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ResponseMessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ResponseMessageType_IsValid(int value);
const ResponseMessageType ResponseMessageType_MIN = CREATE_RESPONSE;
const ResponseMessageType ResponseMessageType_MAX = DELETE_RESPONSE;
const int ResponseMessageType_ARRAYSIZE = ResponseMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ResponseMessageType_descriptor();
inline const ::std::string& ResponseMessageType_Name(ResponseMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ResponseMessageType_descriptor(), value);
}
inline bool ResponseMessageType_Parse(
    const ::std::string& name, ResponseMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResponseMessageType>(
    ResponseMessageType_descriptor(), name, value);
}
// ===================================================================

class CreateRequestFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.CreateRequestFields) */ {
 public:
  CreateRequestFields();
  virtual ~CreateRequestFields();

  CreateRequestFields(const CreateRequestFields& from);

  inline CreateRequestFields& operator=(const CreateRequestFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateRequestFields& default_instance();

  static inline const CreateRequestFields* internal_default_instance() {
    return reinterpret_cast<const CreateRequestFields*>(
               &_CreateRequestFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CreateRequestFields* other);

  // implements Message ----------------------------------------------

  inline CreateRequestFields* New() const PROTOBUF_FINAL { return New(NULL); }

  CreateRequestFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CreateRequestFields& from);
  void MergeFrom(const CreateRequestFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CreateRequestFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:gen.CreateRequestFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UpdateRequestFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.UpdateRequestFields) */ {
 public:
  UpdateRequestFields();
  virtual ~UpdateRequestFields();

  UpdateRequestFields(const UpdateRequestFields& from);

  inline UpdateRequestFields& operator=(const UpdateRequestFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateRequestFields& default_instance();

  static inline const UpdateRequestFields* internal_default_instance() {
    return reinterpret_cast<const UpdateRequestFields*>(
               &_UpdateRequestFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(UpdateRequestFields* other);

  // implements Message ----------------------------------------------

  inline UpdateRequestFields* New() const PROTOBUF_FINAL { return New(NULL); }

  UpdateRequestFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UpdateRequestFields& from);
  void MergeFrom(const UpdateRequestFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UpdateRequestFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:gen.UpdateRequestFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReadRequestFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.ReadRequestFields) */ {
 public:
  ReadRequestFields();
  virtual ~ReadRequestFields();

  ReadRequestFields(const ReadRequestFields& from);

  inline ReadRequestFields& operator=(const ReadRequestFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadRequestFields& default_instance();

  static inline const ReadRequestFields* internal_default_instance() {
    return reinterpret_cast<const ReadRequestFields*>(
               &_ReadRequestFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ReadRequestFields* other);

  // implements Message ----------------------------------------------

  inline ReadRequestFields* New() const PROTOBUF_FINAL { return New(NULL); }

  ReadRequestFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReadRequestFields& from);
  void MergeFrom(const ReadRequestFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReadRequestFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gen.ReadRequestFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteRequestFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.DeleteRequestFields) */ {
 public:
  DeleteRequestFields();
  virtual ~DeleteRequestFields();

  DeleteRequestFields(const DeleteRequestFields& from);

  inline DeleteRequestFields& operator=(const DeleteRequestFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteRequestFields& default_instance();

  static inline const DeleteRequestFields* internal_default_instance() {
    return reinterpret_cast<const DeleteRequestFields*>(
               &_DeleteRequestFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(DeleteRequestFields* other);

  // implements Message ----------------------------------------------

  inline DeleteRequestFields* New() const PROTOBUF_FINAL { return New(NULL); }

  DeleteRequestFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DeleteRequestFields& from);
  void MergeFrom(const DeleteRequestFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DeleteRequestFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gen.DeleteRequestFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RequestMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.RequestMessage) */ {
 public:
  RequestMessage();
  virtual ~RequestMessage();

  RequestMessage(const RequestMessage& from);

  inline RequestMessage& operator=(const RequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestMessage& default_instance();

  enum CustomFieldsCase {
    kCreateFields = 6,
    kUpdateFields = 7,
    kReadFields = 8,
    kDeleteFields = 9,
    CUSTOMFIELDS_NOT_SET = 0,
  };

  static inline const RequestMessage* internal_default_instance() {
    return reinterpret_cast<const RequestMessage*>(
               &_RequestMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(RequestMessage* other);

  // implements Message ----------------------------------------------

  inline RequestMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  RequestMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RequestMessage& from);
  void MergeFrom(const RequestMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RequestMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 4;
  void clear_id();
  static const int kIdFieldNumber = 4;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string key = 5;
  void clear_key();
  static const int kKeyFieldNumber = 5;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // .gen.Address sourceAddress = 2;
  bool has_sourceaddress() const;
  void clear_sourceaddress();
  static const int kSourceAddressFieldNumber = 2;
  const ::gen::Address& sourceaddress() const;
  ::gen::Address* mutable_sourceaddress();
  ::gen::Address* release_sourceaddress();
  void set_allocated_sourceaddress(::gen::Address* sourceaddress);

  // .gen.Address destinationAddress = 3;
  bool has_destinationaddress() const;
  void clear_destinationaddress();
  static const int kDestinationAddressFieldNumber = 3;
  const ::gen::Address& destinationaddress() const;
  ::gen::Address* mutable_destinationaddress();
  ::gen::Address* release_destinationaddress();
  void set_allocated_destinationaddress(::gen::Address* destinationaddress);

  // .gen.RequestMessageType messageType = 1;
  void clear_messagetype();
  static const int kMessageTypeFieldNumber = 1;
  ::gen::RequestMessageType messagetype() const;
  void set_messagetype(::gen::RequestMessageType value);

  // .gen.CreateRequestFields createFields = 6;
  bool has_createfields() const;
  void clear_createfields();
  static const int kCreateFieldsFieldNumber = 6;
  const ::gen::CreateRequestFields& createfields() const;
  ::gen::CreateRequestFields* mutable_createfields();
  ::gen::CreateRequestFields* release_createfields();
  void set_allocated_createfields(::gen::CreateRequestFields* createfields);

  // .gen.UpdateRequestFields updateFields = 7;
  bool has_updatefields() const;
  void clear_updatefields();
  static const int kUpdateFieldsFieldNumber = 7;
  const ::gen::UpdateRequestFields& updatefields() const;
  ::gen::UpdateRequestFields* mutable_updatefields();
  ::gen::UpdateRequestFields* release_updatefields();
  void set_allocated_updatefields(::gen::UpdateRequestFields* updatefields);

  // .gen.ReadRequestFields readFields = 8;
  bool has_readfields() const;
  void clear_readfields();
  static const int kReadFieldsFieldNumber = 8;
  const ::gen::ReadRequestFields& readfields() const;
  ::gen::ReadRequestFields* mutable_readfields();
  ::gen::ReadRequestFields* release_readfields();
  void set_allocated_readfields(::gen::ReadRequestFields* readfields);

  // .gen.DeleteRequestFields deleteFields = 9;
  bool has_deletefields() const;
  void clear_deletefields();
  static const int kDeleteFieldsFieldNumber = 9;
  const ::gen::DeleteRequestFields& deletefields() const;
  ::gen::DeleteRequestFields* mutable_deletefields();
  ::gen::DeleteRequestFields* release_deletefields();
  void set_allocated_deletefields(::gen::DeleteRequestFields* deletefields);

  CustomFieldsCase customFields_case() const;
  // @@protoc_insertion_point(class_scope:gen.RequestMessage)
 private:
  void set_has_createfields();
  void set_has_updatefields();
  void set_has_readfields();
  void set_has_deletefields();

  inline bool has_customFields() const;
  void clear_customFields();
  inline void clear_has_customFields();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::gen::Address* sourceaddress_;
  ::gen::Address* destinationaddress_;
  int messagetype_;
  union CustomFieldsUnion {
    CustomFieldsUnion() {}
    ::gen::CreateRequestFields* createfields_;
    ::gen::UpdateRequestFields* updatefields_;
    ::gen::ReadRequestFields* readfields_;
    ::gen::DeleteRequestFields* deletefields_;
  } customFields_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CreateResponseFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.CreateResponseFields) */ {
 public:
  CreateResponseFields();
  virtual ~CreateResponseFields();

  CreateResponseFields(const CreateResponseFields& from);

  inline CreateResponseFields& operator=(const CreateResponseFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateResponseFields& default_instance();

  static inline const CreateResponseFields* internal_default_instance() {
    return reinterpret_cast<const CreateResponseFields*>(
               &_CreateResponseFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(CreateResponseFields* other);

  // implements Message ----------------------------------------------

  inline CreateResponseFields* New() const PROTOBUF_FINAL { return New(NULL); }

  CreateResponseFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CreateResponseFields& from);
  void MergeFrom(const CreateResponseFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CreateResponseFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gen.CreateResponseFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UpdateResponseFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.UpdateResponseFields) */ {
 public:
  UpdateResponseFields();
  virtual ~UpdateResponseFields();

  UpdateResponseFields(const UpdateResponseFields& from);

  inline UpdateResponseFields& operator=(const UpdateResponseFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateResponseFields& default_instance();

  static inline const UpdateResponseFields* internal_default_instance() {
    return reinterpret_cast<const UpdateResponseFields*>(
               &_UpdateResponseFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(UpdateResponseFields* other);

  // implements Message ----------------------------------------------

  inline UpdateResponseFields* New() const PROTOBUF_FINAL { return New(NULL); }

  UpdateResponseFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UpdateResponseFields& from);
  void MergeFrom(const UpdateResponseFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UpdateResponseFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gen.UpdateResponseFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReadResponseFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.ReadResponseFields) */ {
 public:
  ReadResponseFields();
  virtual ~ReadResponseFields();

  ReadResponseFields(const ReadResponseFields& from);

  inline ReadResponseFields& operator=(const ReadResponseFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadResponseFields& default_instance();

  static inline const ReadResponseFields* internal_default_instance() {
    return reinterpret_cast<const ReadResponseFields*>(
               &_ReadResponseFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(ReadResponseFields* other);

  // implements Message ----------------------------------------------

  inline ReadResponseFields* New() const PROTOBUF_FINAL { return New(NULL); }

  ReadResponseFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReadResponseFields& from);
  void MergeFrom(const ReadResponseFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReadResponseFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gen.ReadResponseFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeleteResponseFields : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.DeleteResponseFields) */ {
 public:
  DeleteResponseFields();
  virtual ~DeleteResponseFields();

  DeleteResponseFields(const DeleteResponseFields& from);

  inline DeleteResponseFields& operator=(const DeleteResponseFields& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteResponseFields& default_instance();

  static inline const DeleteResponseFields* internal_default_instance() {
    return reinterpret_cast<const DeleteResponseFields*>(
               &_DeleteResponseFields_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(DeleteResponseFields* other);

  // implements Message ----------------------------------------------

  inline DeleteResponseFields* New() const PROTOBUF_FINAL { return New(NULL); }

  DeleteResponseFields* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DeleteResponseFields& from);
  void MergeFrom(const DeleteResponseFields& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DeleteResponseFields* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gen.DeleteResponseFields)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResponseMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.ResponseMessage) */ {
 public:
  ResponseMessage();
  virtual ~ResponseMessage();

  ResponseMessage(const ResponseMessage& from);

  inline ResponseMessage& operator=(const ResponseMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseMessage& default_instance();

  enum CustomFieldsCase {
    kCreateFields = 7,
    kUpdateFields = 8,
    kReadFields = 9,
    kDeleteFields = 10,
    CUSTOMFIELDS_NOT_SET = 0,
  };

  static inline const ResponseMessage* internal_default_instance() {
    return reinterpret_cast<const ResponseMessage*>(
               &_ResponseMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(ResponseMessage* other);

  // implements Message ----------------------------------------------

  inline ResponseMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  ResponseMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResponseMessage& from);
  void MergeFrom(const ResponseMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResponseMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 4;
  void clear_id();
  static const int kIdFieldNumber = 4;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string originalMessageId = 5;
  void clear_originalmessageid();
  static const int kOriginalMessageIdFieldNumber = 5;
  const ::std::string& originalmessageid() const;
  void set_originalmessageid(const ::std::string& value);
  #if LANG_CXX11
  void set_originalmessageid(::std::string&& value);
  #endif
  void set_originalmessageid(const char* value);
  void set_originalmessageid(const char* value, size_t size);
  ::std::string* mutable_originalmessageid();
  ::std::string* release_originalmessageid();
  void set_allocated_originalmessageid(::std::string* originalmessageid);

  // .gen.Address sourceAddress = 2;
  bool has_sourceaddress() const;
  void clear_sourceaddress();
  static const int kSourceAddressFieldNumber = 2;
  const ::gen::Address& sourceaddress() const;
  ::gen::Address* mutable_sourceaddress();
  ::gen::Address* release_sourceaddress();
  void set_allocated_sourceaddress(::gen::Address* sourceaddress);

  // .gen.Address destinationAddress = 3;
  bool has_destinationaddress() const;
  void clear_destinationaddress();
  static const int kDestinationAddressFieldNumber = 3;
  const ::gen::Address& destinationaddress() const;
  ::gen::Address* mutable_destinationaddress();
  ::gen::Address* release_destinationaddress();
  void set_allocated_destinationaddress(::gen::Address* destinationaddress);

  // .gen.ResponseMessageType messageType = 1;
  void clear_messagetype();
  static const int kMessageTypeFieldNumber = 1;
  ::gen::ResponseMessageType messagetype() const;
  void set_messagetype(::gen::ResponseMessageType value);

  // int32 responseCode = 6;
  void clear_responsecode();
  static const int kResponseCodeFieldNumber = 6;
  ::google::protobuf::int32 responsecode() const;
  void set_responsecode(::google::protobuf::int32 value);

  // .gen.CreateResponseFields createFields = 7;
  bool has_createfields() const;
  void clear_createfields();
  static const int kCreateFieldsFieldNumber = 7;
  const ::gen::CreateResponseFields& createfields() const;
  ::gen::CreateResponseFields* mutable_createfields();
  ::gen::CreateResponseFields* release_createfields();
  void set_allocated_createfields(::gen::CreateResponseFields* createfields);

  // .gen.UpdateResponseFields updateFields = 8;
  bool has_updatefields() const;
  void clear_updatefields();
  static const int kUpdateFieldsFieldNumber = 8;
  const ::gen::UpdateResponseFields& updatefields() const;
  ::gen::UpdateResponseFields* mutable_updatefields();
  ::gen::UpdateResponseFields* release_updatefields();
  void set_allocated_updatefields(::gen::UpdateResponseFields* updatefields);

  // .gen.ReadResponseFields readFields = 9;
  bool has_readfields() const;
  void clear_readfields();
  static const int kReadFieldsFieldNumber = 9;
  const ::gen::ReadResponseFields& readfields() const;
  ::gen::ReadResponseFields* mutable_readfields();
  ::gen::ReadResponseFields* release_readfields();
  void set_allocated_readfields(::gen::ReadResponseFields* readfields);

  // .gen.DeleteResponseFields deleteFields = 10;
  bool has_deletefields() const;
  void clear_deletefields();
  static const int kDeleteFieldsFieldNumber = 10;
  const ::gen::DeleteResponseFields& deletefields() const;
  ::gen::DeleteResponseFields* mutable_deletefields();
  ::gen::DeleteResponseFields* release_deletefields();
  void set_allocated_deletefields(::gen::DeleteResponseFields* deletefields);

  CustomFieldsCase customFields_case() const;
  // @@protoc_insertion_point(class_scope:gen.ResponseMessage)
 private:
  void set_has_createfields();
  void set_has_updatefields();
  void set_has_readfields();
  void set_has_deletefields();

  inline bool has_customFields() const;
  void clear_customFields();
  inline void clear_has_customFields();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr originalmessageid_;
  ::gen::Address* sourceaddress_;
  ::gen::Address* destinationaddress_;
  int messagetype_;
  ::google::protobuf::int32 responsecode_;
  union CustomFieldsUnion {
    CustomFieldsUnion() {}
    ::gen::CreateResponseFields* createfields_;
    ::gen::UpdateResponseFields* updatefields_;
    ::gen::ReadResponseFields* readfields_;
    ::gen::DeleteResponseFields* deletefields_;
  } customFields_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct protobuf_KeyValueStoreMessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CreateRequestFields

// string value = 1;
inline void CreateRequestFields::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateRequestFields::value() const {
  // @@protoc_insertion_point(field_get:gen.CreateRequestFields.value)
  return value_.GetNoArena();
}
inline void CreateRequestFields::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gen.CreateRequestFields.value)
}
#if LANG_CXX11
inline void CreateRequestFields::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gen.CreateRequestFields.value)
}
#endif
inline void CreateRequestFields::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gen.CreateRequestFields.value)
}
inline void CreateRequestFields::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gen.CreateRequestFields.value)
}
inline ::std::string* CreateRequestFields::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:gen.CreateRequestFields.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateRequestFields::release_value() {
  // @@protoc_insertion_point(field_release:gen.CreateRequestFields.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateRequestFields::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:gen.CreateRequestFields.value)
}

// -------------------------------------------------------------------

// UpdateRequestFields

// string value = 1;
inline void UpdateRequestFields::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UpdateRequestFields::value() const {
  // @@protoc_insertion_point(field_get:gen.UpdateRequestFields.value)
  return value_.GetNoArena();
}
inline void UpdateRequestFields::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gen.UpdateRequestFields.value)
}
#if LANG_CXX11
inline void UpdateRequestFields::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gen.UpdateRequestFields.value)
}
#endif
inline void UpdateRequestFields::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gen.UpdateRequestFields.value)
}
inline void UpdateRequestFields::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gen.UpdateRequestFields.value)
}
inline ::std::string* UpdateRequestFields::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:gen.UpdateRequestFields.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UpdateRequestFields::release_value() {
  // @@protoc_insertion_point(field_release:gen.UpdateRequestFields.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UpdateRequestFields::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:gen.UpdateRequestFields.value)
}

// -------------------------------------------------------------------

// ReadRequestFields

// -------------------------------------------------------------------

// DeleteRequestFields

// -------------------------------------------------------------------

// RequestMessage

// .gen.RequestMessageType messageType = 1;
inline void RequestMessage::clear_messagetype() {
  messagetype_ = 0;
}
inline ::gen::RequestMessageType RequestMessage::messagetype() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.messageType)
  return static_cast< ::gen::RequestMessageType >(messagetype_);
}
inline void RequestMessage::set_messagetype(::gen::RequestMessageType value) {
  
  messagetype_ = value;
  // @@protoc_insertion_point(field_set:gen.RequestMessage.messageType)
}

// .gen.Address sourceAddress = 2;
inline bool RequestMessage::has_sourceaddress() const {
  return this != internal_default_instance() && sourceaddress_ != NULL;
}
inline void RequestMessage::clear_sourceaddress() {
  if (GetArenaNoVirtual() == NULL && sourceaddress_ != NULL) delete sourceaddress_;
  sourceaddress_ = NULL;
}
inline const ::gen::Address& RequestMessage::sourceaddress() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.sourceAddress)
  return sourceaddress_ != NULL ? *sourceaddress_
                         : *::gen::Address::internal_default_instance();
}
inline ::gen::Address* RequestMessage::mutable_sourceaddress() {
  
  if (sourceaddress_ == NULL) {
    sourceaddress_ = new ::gen::Address;
  }
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.sourceAddress)
  return sourceaddress_;
}
inline ::gen::Address* RequestMessage::release_sourceaddress() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.sourceAddress)
  
  ::gen::Address* temp = sourceaddress_;
  sourceaddress_ = NULL;
  return temp;
}
inline void RequestMessage::set_allocated_sourceaddress(::gen::Address* sourceaddress) {
  delete sourceaddress_;
  sourceaddress_ = sourceaddress;
  if (sourceaddress) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.sourceAddress)
}

// .gen.Address destinationAddress = 3;
inline bool RequestMessage::has_destinationaddress() const {
  return this != internal_default_instance() && destinationaddress_ != NULL;
}
inline void RequestMessage::clear_destinationaddress() {
  if (GetArenaNoVirtual() == NULL && destinationaddress_ != NULL) delete destinationaddress_;
  destinationaddress_ = NULL;
}
inline const ::gen::Address& RequestMessage::destinationaddress() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.destinationAddress)
  return destinationaddress_ != NULL ? *destinationaddress_
                         : *::gen::Address::internal_default_instance();
}
inline ::gen::Address* RequestMessage::mutable_destinationaddress() {
  
  if (destinationaddress_ == NULL) {
    destinationaddress_ = new ::gen::Address;
  }
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.destinationAddress)
  return destinationaddress_;
}
inline ::gen::Address* RequestMessage::release_destinationaddress() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.destinationAddress)
  
  ::gen::Address* temp = destinationaddress_;
  destinationaddress_ = NULL;
  return temp;
}
inline void RequestMessage::set_allocated_destinationaddress(::gen::Address* destinationaddress) {
  delete destinationaddress_;
  destinationaddress_ = destinationaddress;
  if (destinationaddress) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.destinationAddress)
}

// string id = 4;
inline void RequestMessage::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RequestMessage::id() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.id)
  return id_.GetNoArena();
}
inline void RequestMessage::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gen.RequestMessage.id)
}
#if LANG_CXX11
inline void RequestMessage::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gen.RequestMessage.id)
}
#endif
inline void RequestMessage::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gen.RequestMessage.id)
}
inline void RequestMessage::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gen.RequestMessage.id)
}
inline ::std::string* RequestMessage::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestMessage::release_id() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestMessage::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.id)
}

// string key = 5;
inline void RequestMessage::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RequestMessage::key() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.key)
  return key_.GetNoArena();
}
inline void RequestMessage::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gen.RequestMessage.key)
}
#if LANG_CXX11
inline void RequestMessage::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gen.RequestMessage.key)
}
#endif
inline void RequestMessage::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gen.RequestMessage.key)
}
inline void RequestMessage::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gen.RequestMessage.key)
}
inline ::std::string* RequestMessage::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestMessage::release_key() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestMessage::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.key)
}

// .gen.CreateRequestFields createFields = 6;
inline bool RequestMessage::has_createfields() const {
  return customFields_case() == kCreateFields;
}
inline void RequestMessage::set_has_createfields() {
  _oneof_case_[0] = kCreateFields;
}
inline void RequestMessage::clear_createfields() {
  if (has_createfields()) {
    delete customFields_.createfields_;
    clear_has_customFields();
  }
}
inline  const ::gen::CreateRequestFields& RequestMessage::createfields() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.createFields)
  return has_createfields()
      ? *customFields_.createfields_
      : ::gen::CreateRequestFields::default_instance();
}
inline ::gen::CreateRequestFields* RequestMessage::mutable_createfields() {
  if (!has_createfields()) {
    clear_customFields();
    set_has_createfields();
    customFields_.createfields_ = new ::gen::CreateRequestFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.createFields)
  return customFields_.createfields_;
}
inline ::gen::CreateRequestFields* RequestMessage::release_createfields() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.createFields)
  if (has_createfields()) {
    clear_has_customFields();
    ::gen::CreateRequestFields* temp = customFields_.createfields_;
    customFields_.createfields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RequestMessage::set_allocated_createfields(::gen::CreateRequestFields* createfields) {
  clear_customFields();
  if (createfields) {
    set_has_createfields();
    customFields_.createfields_ = createfields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.createFields)
}

// .gen.UpdateRequestFields updateFields = 7;
inline bool RequestMessage::has_updatefields() const {
  return customFields_case() == kUpdateFields;
}
inline void RequestMessage::set_has_updatefields() {
  _oneof_case_[0] = kUpdateFields;
}
inline void RequestMessage::clear_updatefields() {
  if (has_updatefields()) {
    delete customFields_.updatefields_;
    clear_has_customFields();
  }
}
inline  const ::gen::UpdateRequestFields& RequestMessage::updatefields() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.updateFields)
  return has_updatefields()
      ? *customFields_.updatefields_
      : ::gen::UpdateRequestFields::default_instance();
}
inline ::gen::UpdateRequestFields* RequestMessage::mutable_updatefields() {
  if (!has_updatefields()) {
    clear_customFields();
    set_has_updatefields();
    customFields_.updatefields_ = new ::gen::UpdateRequestFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.updateFields)
  return customFields_.updatefields_;
}
inline ::gen::UpdateRequestFields* RequestMessage::release_updatefields() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.updateFields)
  if (has_updatefields()) {
    clear_has_customFields();
    ::gen::UpdateRequestFields* temp = customFields_.updatefields_;
    customFields_.updatefields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RequestMessage::set_allocated_updatefields(::gen::UpdateRequestFields* updatefields) {
  clear_customFields();
  if (updatefields) {
    set_has_updatefields();
    customFields_.updatefields_ = updatefields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.updateFields)
}

// .gen.ReadRequestFields readFields = 8;
inline bool RequestMessage::has_readfields() const {
  return customFields_case() == kReadFields;
}
inline void RequestMessage::set_has_readfields() {
  _oneof_case_[0] = kReadFields;
}
inline void RequestMessage::clear_readfields() {
  if (has_readfields()) {
    delete customFields_.readfields_;
    clear_has_customFields();
  }
}
inline  const ::gen::ReadRequestFields& RequestMessage::readfields() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.readFields)
  return has_readfields()
      ? *customFields_.readfields_
      : ::gen::ReadRequestFields::default_instance();
}
inline ::gen::ReadRequestFields* RequestMessage::mutable_readfields() {
  if (!has_readfields()) {
    clear_customFields();
    set_has_readfields();
    customFields_.readfields_ = new ::gen::ReadRequestFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.readFields)
  return customFields_.readfields_;
}
inline ::gen::ReadRequestFields* RequestMessage::release_readfields() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.readFields)
  if (has_readfields()) {
    clear_has_customFields();
    ::gen::ReadRequestFields* temp = customFields_.readfields_;
    customFields_.readfields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RequestMessage::set_allocated_readfields(::gen::ReadRequestFields* readfields) {
  clear_customFields();
  if (readfields) {
    set_has_readfields();
    customFields_.readfields_ = readfields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.readFields)
}

// .gen.DeleteRequestFields deleteFields = 9;
inline bool RequestMessage::has_deletefields() const {
  return customFields_case() == kDeleteFields;
}
inline void RequestMessage::set_has_deletefields() {
  _oneof_case_[0] = kDeleteFields;
}
inline void RequestMessage::clear_deletefields() {
  if (has_deletefields()) {
    delete customFields_.deletefields_;
    clear_has_customFields();
  }
}
inline  const ::gen::DeleteRequestFields& RequestMessage::deletefields() const {
  // @@protoc_insertion_point(field_get:gen.RequestMessage.deleteFields)
  return has_deletefields()
      ? *customFields_.deletefields_
      : ::gen::DeleteRequestFields::default_instance();
}
inline ::gen::DeleteRequestFields* RequestMessage::mutable_deletefields() {
  if (!has_deletefields()) {
    clear_customFields();
    set_has_deletefields();
    customFields_.deletefields_ = new ::gen::DeleteRequestFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.RequestMessage.deleteFields)
  return customFields_.deletefields_;
}
inline ::gen::DeleteRequestFields* RequestMessage::release_deletefields() {
  // @@protoc_insertion_point(field_release:gen.RequestMessage.deleteFields)
  if (has_deletefields()) {
    clear_has_customFields();
    ::gen::DeleteRequestFields* temp = customFields_.deletefields_;
    customFields_.deletefields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RequestMessage::set_allocated_deletefields(::gen::DeleteRequestFields* deletefields) {
  clear_customFields();
  if (deletefields) {
    set_has_deletefields();
    customFields_.deletefields_ = deletefields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.RequestMessage.deleteFields)
}

inline bool RequestMessage::has_customFields() const {
  return customFields_case() != CUSTOMFIELDS_NOT_SET;
}
inline void RequestMessage::clear_has_customFields() {
  _oneof_case_[0] = CUSTOMFIELDS_NOT_SET;
}
inline RequestMessage::CustomFieldsCase RequestMessage::customFields_case() const {
  return RequestMessage::CustomFieldsCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// CreateResponseFields

// -------------------------------------------------------------------

// UpdateResponseFields

// -------------------------------------------------------------------

// ReadResponseFields

// -------------------------------------------------------------------

// DeleteResponseFields

// -------------------------------------------------------------------

// ResponseMessage

// .gen.ResponseMessageType messageType = 1;
inline void ResponseMessage::clear_messagetype() {
  messagetype_ = 0;
}
inline ::gen::ResponseMessageType ResponseMessage::messagetype() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.messageType)
  return static_cast< ::gen::ResponseMessageType >(messagetype_);
}
inline void ResponseMessage::set_messagetype(::gen::ResponseMessageType value) {
  
  messagetype_ = value;
  // @@protoc_insertion_point(field_set:gen.ResponseMessage.messageType)
}

// .gen.Address sourceAddress = 2;
inline bool ResponseMessage::has_sourceaddress() const {
  return this != internal_default_instance() && sourceaddress_ != NULL;
}
inline void ResponseMessage::clear_sourceaddress() {
  if (GetArenaNoVirtual() == NULL && sourceaddress_ != NULL) delete sourceaddress_;
  sourceaddress_ = NULL;
}
inline const ::gen::Address& ResponseMessage::sourceaddress() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.sourceAddress)
  return sourceaddress_ != NULL ? *sourceaddress_
                         : *::gen::Address::internal_default_instance();
}
inline ::gen::Address* ResponseMessage::mutable_sourceaddress() {
  
  if (sourceaddress_ == NULL) {
    sourceaddress_ = new ::gen::Address;
  }
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.sourceAddress)
  return sourceaddress_;
}
inline ::gen::Address* ResponseMessage::release_sourceaddress() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.sourceAddress)
  
  ::gen::Address* temp = sourceaddress_;
  sourceaddress_ = NULL;
  return temp;
}
inline void ResponseMessage::set_allocated_sourceaddress(::gen::Address* sourceaddress) {
  delete sourceaddress_;
  sourceaddress_ = sourceaddress;
  if (sourceaddress) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.sourceAddress)
}

// .gen.Address destinationAddress = 3;
inline bool ResponseMessage::has_destinationaddress() const {
  return this != internal_default_instance() && destinationaddress_ != NULL;
}
inline void ResponseMessage::clear_destinationaddress() {
  if (GetArenaNoVirtual() == NULL && destinationaddress_ != NULL) delete destinationaddress_;
  destinationaddress_ = NULL;
}
inline const ::gen::Address& ResponseMessage::destinationaddress() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.destinationAddress)
  return destinationaddress_ != NULL ? *destinationaddress_
                         : *::gen::Address::internal_default_instance();
}
inline ::gen::Address* ResponseMessage::mutable_destinationaddress() {
  
  if (destinationaddress_ == NULL) {
    destinationaddress_ = new ::gen::Address;
  }
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.destinationAddress)
  return destinationaddress_;
}
inline ::gen::Address* ResponseMessage::release_destinationaddress() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.destinationAddress)
  
  ::gen::Address* temp = destinationaddress_;
  destinationaddress_ = NULL;
  return temp;
}
inline void ResponseMessage::set_allocated_destinationaddress(::gen::Address* destinationaddress) {
  delete destinationaddress_;
  destinationaddress_ = destinationaddress;
  if (destinationaddress) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.destinationAddress)
}

// string id = 4;
inline void ResponseMessage::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResponseMessage::id() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.id)
  return id_.GetNoArena();
}
inline void ResponseMessage::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gen.ResponseMessage.id)
}
#if LANG_CXX11
inline void ResponseMessage::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gen.ResponseMessage.id)
}
#endif
inline void ResponseMessage::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gen.ResponseMessage.id)
}
inline void ResponseMessage::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gen.ResponseMessage.id)
}
inline ::std::string* ResponseMessage::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponseMessage::release_id() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponseMessage::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.id)
}

// string originalMessageId = 5;
inline void ResponseMessage::clear_originalmessageid() {
  originalmessageid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ResponseMessage::originalmessageid() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.originalMessageId)
  return originalmessageid_.GetNoArena();
}
inline void ResponseMessage::set_originalmessageid(const ::std::string& value) {
  
  originalmessageid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gen.ResponseMessage.originalMessageId)
}
#if LANG_CXX11
inline void ResponseMessage::set_originalmessageid(::std::string&& value) {
  
  originalmessageid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gen.ResponseMessage.originalMessageId)
}
#endif
inline void ResponseMessage::set_originalmessageid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  originalmessageid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gen.ResponseMessage.originalMessageId)
}
inline void ResponseMessage::set_originalmessageid(const char* value, size_t size) {
  
  originalmessageid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gen.ResponseMessage.originalMessageId)
}
inline ::std::string* ResponseMessage::mutable_originalmessageid() {
  
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.originalMessageId)
  return originalmessageid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ResponseMessage::release_originalmessageid() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.originalMessageId)
  
  return originalmessageid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ResponseMessage::set_allocated_originalmessageid(::std::string* originalmessageid) {
  if (originalmessageid != NULL) {
    
  } else {
    
  }
  originalmessageid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), originalmessageid);
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.originalMessageId)
}

// int32 responseCode = 6;
inline void ResponseMessage::clear_responsecode() {
  responsecode_ = 0;
}
inline ::google::protobuf::int32 ResponseMessage::responsecode() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.responseCode)
  return responsecode_;
}
inline void ResponseMessage::set_responsecode(::google::protobuf::int32 value) {
  
  responsecode_ = value;
  // @@protoc_insertion_point(field_set:gen.ResponseMessage.responseCode)
}

// .gen.CreateResponseFields createFields = 7;
inline bool ResponseMessage::has_createfields() const {
  return customFields_case() == kCreateFields;
}
inline void ResponseMessage::set_has_createfields() {
  _oneof_case_[0] = kCreateFields;
}
inline void ResponseMessage::clear_createfields() {
  if (has_createfields()) {
    delete customFields_.createfields_;
    clear_has_customFields();
  }
}
inline  const ::gen::CreateResponseFields& ResponseMessage::createfields() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.createFields)
  return has_createfields()
      ? *customFields_.createfields_
      : ::gen::CreateResponseFields::default_instance();
}
inline ::gen::CreateResponseFields* ResponseMessage::mutable_createfields() {
  if (!has_createfields()) {
    clear_customFields();
    set_has_createfields();
    customFields_.createfields_ = new ::gen::CreateResponseFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.createFields)
  return customFields_.createfields_;
}
inline ::gen::CreateResponseFields* ResponseMessage::release_createfields() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.createFields)
  if (has_createfields()) {
    clear_has_customFields();
    ::gen::CreateResponseFields* temp = customFields_.createfields_;
    customFields_.createfields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ResponseMessage::set_allocated_createfields(::gen::CreateResponseFields* createfields) {
  clear_customFields();
  if (createfields) {
    set_has_createfields();
    customFields_.createfields_ = createfields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.createFields)
}

// .gen.UpdateResponseFields updateFields = 8;
inline bool ResponseMessage::has_updatefields() const {
  return customFields_case() == kUpdateFields;
}
inline void ResponseMessage::set_has_updatefields() {
  _oneof_case_[0] = kUpdateFields;
}
inline void ResponseMessage::clear_updatefields() {
  if (has_updatefields()) {
    delete customFields_.updatefields_;
    clear_has_customFields();
  }
}
inline  const ::gen::UpdateResponseFields& ResponseMessage::updatefields() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.updateFields)
  return has_updatefields()
      ? *customFields_.updatefields_
      : ::gen::UpdateResponseFields::default_instance();
}
inline ::gen::UpdateResponseFields* ResponseMessage::mutable_updatefields() {
  if (!has_updatefields()) {
    clear_customFields();
    set_has_updatefields();
    customFields_.updatefields_ = new ::gen::UpdateResponseFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.updateFields)
  return customFields_.updatefields_;
}
inline ::gen::UpdateResponseFields* ResponseMessage::release_updatefields() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.updateFields)
  if (has_updatefields()) {
    clear_has_customFields();
    ::gen::UpdateResponseFields* temp = customFields_.updatefields_;
    customFields_.updatefields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ResponseMessage::set_allocated_updatefields(::gen::UpdateResponseFields* updatefields) {
  clear_customFields();
  if (updatefields) {
    set_has_updatefields();
    customFields_.updatefields_ = updatefields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.updateFields)
}

// .gen.ReadResponseFields readFields = 9;
inline bool ResponseMessage::has_readfields() const {
  return customFields_case() == kReadFields;
}
inline void ResponseMessage::set_has_readfields() {
  _oneof_case_[0] = kReadFields;
}
inline void ResponseMessage::clear_readfields() {
  if (has_readfields()) {
    delete customFields_.readfields_;
    clear_has_customFields();
  }
}
inline  const ::gen::ReadResponseFields& ResponseMessage::readfields() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.readFields)
  return has_readfields()
      ? *customFields_.readfields_
      : ::gen::ReadResponseFields::default_instance();
}
inline ::gen::ReadResponseFields* ResponseMessage::mutable_readfields() {
  if (!has_readfields()) {
    clear_customFields();
    set_has_readfields();
    customFields_.readfields_ = new ::gen::ReadResponseFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.readFields)
  return customFields_.readfields_;
}
inline ::gen::ReadResponseFields* ResponseMessage::release_readfields() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.readFields)
  if (has_readfields()) {
    clear_has_customFields();
    ::gen::ReadResponseFields* temp = customFields_.readfields_;
    customFields_.readfields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ResponseMessage::set_allocated_readfields(::gen::ReadResponseFields* readfields) {
  clear_customFields();
  if (readfields) {
    set_has_readfields();
    customFields_.readfields_ = readfields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.readFields)
}

// .gen.DeleteResponseFields deleteFields = 10;
inline bool ResponseMessage::has_deletefields() const {
  return customFields_case() == kDeleteFields;
}
inline void ResponseMessage::set_has_deletefields() {
  _oneof_case_[0] = kDeleteFields;
}
inline void ResponseMessage::clear_deletefields() {
  if (has_deletefields()) {
    delete customFields_.deletefields_;
    clear_has_customFields();
  }
}
inline  const ::gen::DeleteResponseFields& ResponseMessage::deletefields() const {
  // @@protoc_insertion_point(field_get:gen.ResponseMessage.deleteFields)
  return has_deletefields()
      ? *customFields_.deletefields_
      : ::gen::DeleteResponseFields::default_instance();
}
inline ::gen::DeleteResponseFields* ResponseMessage::mutable_deletefields() {
  if (!has_deletefields()) {
    clear_customFields();
    set_has_deletefields();
    customFields_.deletefields_ = new ::gen::DeleteResponseFields;
  }
  // @@protoc_insertion_point(field_mutable:gen.ResponseMessage.deleteFields)
  return customFields_.deletefields_;
}
inline ::gen::DeleteResponseFields* ResponseMessage::release_deletefields() {
  // @@protoc_insertion_point(field_release:gen.ResponseMessage.deleteFields)
  if (has_deletefields()) {
    clear_has_customFields();
    ::gen::DeleteResponseFields* temp = customFields_.deletefields_;
    customFields_.deletefields_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void ResponseMessage::set_allocated_deletefields(::gen::DeleteResponseFields* deletefields) {
  clear_customFields();
  if (deletefields) {
    set_has_deletefields();
    customFields_.deletefields_ = deletefields;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.ResponseMessage.deleteFields)
}

inline bool ResponseMessage::has_customFields() const {
  return customFields_case() != CUSTOMFIELDS_NOT_SET;
}
inline void ResponseMessage::clear_has_customFields() {
  _oneof_case_[0] = CUSTOMFIELDS_NOT_SET;
}
inline ResponseMessage::CustomFieldsCase ResponseMessage::customFields_case() const {
  return ResponseMessage::CustomFieldsCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace gen

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::gen::RequestMessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gen::RequestMessageType>() {
  return ::gen::RequestMessageType_descriptor();
}
template <> struct is_proto_enum< ::gen::ResponseMessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gen::ResponseMessageType>() {
  return ::gen::ResponseMessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_KeyValueStoreMessage_2eproto__INCLUDED
