// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WrapperMessage.proto

#ifndef PROTOBUF_WrapperMessage_2eproto__INCLUDED
#define PROTOBUF_WrapperMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Address.pb.h"
#include "KeyValueStoreMessage.pb.h"
#include "MembershipProtocolMessage.pb.h"
// @@protoc_insertion_point(includes)
namespace gen {
class Address;
class AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
namespace key_value_store {
class CreateRequestFields;
class CreateRequestFieldsDefaultTypeInternal;
extern CreateRequestFieldsDefaultTypeInternal _CreateRequestFields_default_instance_;
class CreateResponseFields;
class CreateResponseFieldsDefaultTypeInternal;
extern CreateResponseFieldsDefaultTypeInternal _CreateResponseFields_default_instance_;
class DeleteRequestFields;
class DeleteRequestFieldsDefaultTypeInternal;
extern DeleteRequestFieldsDefaultTypeInternal _DeleteRequestFields_default_instance_;
class DeleteResponseFields;
class DeleteResponseFieldsDefaultTypeInternal;
extern DeleteResponseFieldsDefaultTypeInternal _DeleteResponseFields_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class ReadRequestFields;
class ReadRequestFieldsDefaultTypeInternal;
extern ReadRequestFieldsDefaultTypeInternal _ReadRequestFields_default_instance_;
class ReadResponseFields;
class ReadResponseFieldsDefaultTypeInternal;
extern ReadResponseFieldsDefaultTypeInternal _ReadResponseFields_default_instance_;
class RequestMessage;
class RequestMessageDefaultTypeInternal;
extern RequestMessageDefaultTypeInternal _RequestMessage_default_instance_;
class ResponseMessage;
class ResponseMessageDefaultTypeInternal;
extern ResponseMessageDefaultTypeInternal _ResponseMessage_default_instance_;
class UpdateRequestFields;
class UpdateRequestFieldsDefaultTypeInternal;
extern UpdateRequestFieldsDefaultTypeInternal _UpdateRequestFields_default_instance_;
class UpdateResponseFields;
class UpdateResponseFieldsDefaultTypeInternal;
extern UpdateResponseFieldsDefaultTypeInternal _UpdateResponseFields_default_instance_;
}  // namespace key_value_store
namespace membership_protocol {
class AckFields;
class AckFieldsDefaultTypeInternal;
extern AckFieldsDefaultTypeInternal _AckFields_default_instance_;
class Gossip;
class GossipDefaultTypeInternal;
extern GossipDefaultTypeInternal _Gossip_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class PingFields;
class PingFieldsDefaultTypeInternal;
extern PingFieldsDefaultTypeInternal _PingFields_default_instance_;
class PingReqFields;
class PingReqFieldsDefaultTypeInternal;
extern PingReqFieldsDefaultTypeInternal _PingReqFields_default_instance_;
}  // namespace membership_protocol
}  // namespace gen

namespace gen {

namespace protobuf_WrapperMessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_WrapperMessage_2eproto

// ===================================================================

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gen.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  enum MessageInternalCase {
    kKeyValueStoreMessage = 4,
    kMembershipProtocolMessage = 5,
    MESSAGEINTERNAL_NOT_SET = 0,
  };

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 3;
  void clear_id();
  static const int kIdFieldNumber = 3;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // .gen.Address sourceAddress = 1;
  bool has_sourceaddress() const;
  void clear_sourceaddress();
  static const int kSourceAddressFieldNumber = 1;
  const ::gen::Address& sourceaddress() const;
  ::gen::Address* mutable_sourceaddress();
  ::gen::Address* release_sourceaddress();
  void set_allocated_sourceaddress(::gen::Address* sourceaddress);

  // .gen.Address destinationAddress = 2;
  bool has_destinationaddress() const;
  void clear_destinationaddress();
  static const int kDestinationAddressFieldNumber = 2;
  const ::gen::Address& destinationaddress() const;
  ::gen::Address* mutable_destinationaddress();
  ::gen::Address* release_destinationaddress();
  void set_allocated_destinationaddress(::gen::Address* destinationaddress);

  // .gen.key_value_store.Message keyValueStoreMessage = 4;
  bool has_keyvaluestoremessage() const;
  void clear_keyvaluestoremessage();
  static const int kKeyValueStoreMessageFieldNumber = 4;
  const ::gen::key_value_store::Message& keyvaluestoremessage() const;
  ::gen::key_value_store::Message* mutable_keyvaluestoremessage();
  ::gen::key_value_store::Message* release_keyvaluestoremessage();
  void set_allocated_keyvaluestoremessage(::gen::key_value_store::Message* keyvaluestoremessage);

  // .gen.membership_protocol.Message membershipProtocolMessage = 5;
  bool has_membershipprotocolmessage() const;
  void clear_membershipprotocolmessage();
  static const int kMembershipProtocolMessageFieldNumber = 5;
  const ::gen::membership_protocol::Message& membershipprotocolmessage() const;
  ::gen::membership_protocol::Message* mutable_membershipprotocolmessage();
  ::gen::membership_protocol::Message* release_membershipprotocolmessage();
  void set_allocated_membershipprotocolmessage(::gen::membership_protocol::Message* membershipprotocolmessage);

  MessageInternalCase messageInternal_case() const;
  // @@protoc_insertion_point(class_scope:gen.Message)
 private:
  void set_has_keyvaluestoremessage();
  void set_has_membershipprotocolmessage();

  inline bool has_messageInternal() const;
  void clear_messageInternal();
  inline void clear_has_messageInternal();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::gen::Address* sourceaddress_;
  ::gen::Address* destinationaddress_;
  union MessageInternalUnion {
    MessageInternalUnion() {}
    ::gen::key_value_store::Message* keyvaluestoremessage_;
    ::gen::membership_protocol::Message* membershipprotocolmessage_;
  } messageInternal_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct protobuf_WrapperMessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Message

// .gen.Address sourceAddress = 1;
inline bool Message::has_sourceaddress() const {
  return this != internal_default_instance() && sourceaddress_ != NULL;
}
inline void Message::clear_sourceaddress() {
  if (GetArenaNoVirtual() == NULL && sourceaddress_ != NULL) delete sourceaddress_;
  sourceaddress_ = NULL;
}
inline const ::gen::Address& Message::sourceaddress() const {
  // @@protoc_insertion_point(field_get:gen.Message.sourceAddress)
  return sourceaddress_ != NULL ? *sourceaddress_
                         : *::gen::Address::internal_default_instance();
}
inline ::gen::Address* Message::mutable_sourceaddress() {
  
  if (sourceaddress_ == NULL) {
    sourceaddress_ = new ::gen::Address;
  }
  // @@protoc_insertion_point(field_mutable:gen.Message.sourceAddress)
  return sourceaddress_;
}
inline ::gen::Address* Message::release_sourceaddress() {
  // @@protoc_insertion_point(field_release:gen.Message.sourceAddress)
  
  ::gen::Address* temp = sourceaddress_;
  sourceaddress_ = NULL;
  return temp;
}
inline void Message::set_allocated_sourceaddress(::gen::Address* sourceaddress) {
  delete sourceaddress_;
  sourceaddress_ = sourceaddress;
  if (sourceaddress) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gen.Message.sourceAddress)
}

// .gen.Address destinationAddress = 2;
inline bool Message::has_destinationaddress() const {
  return this != internal_default_instance() && destinationaddress_ != NULL;
}
inline void Message::clear_destinationaddress() {
  if (GetArenaNoVirtual() == NULL && destinationaddress_ != NULL) delete destinationaddress_;
  destinationaddress_ = NULL;
}
inline const ::gen::Address& Message::destinationaddress() const {
  // @@protoc_insertion_point(field_get:gen.Message.destinationAddress)
  return destinationaddress_ != NULL ? *destinationaddress_
                         : *::gen::Address::internal_default_instance();
}
inline ::gen::Address* Message::mutable_destinationaddress() {
  
  if (destinationaddress_ == NULL) {
    destinationaddress_ = new ::gen::Address;
  }
  // @@protoc_insertion_point(field_mutable:gen.Message.destinationAddress)
  return destinationaddress_;
}
inline ::gen::Address* Message::release_destinationaddress() {
  // @@protoc_insertion_point(field_release:gen.Message.destinationAddress)
  
  ::gen::Address* temp = destinationaddress_;
  destinationaddress_ = NULL;
  return temp;
}
inline void Message::set_allocated_destinationaddress(::gen::Address* destinationaddress) {
  delete destinationaddress_;
  destinationaddress_ = destinationaddress;
  if (destinationaddress) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gen.Message.destinationAddress)
}

// string id = 3;
inline void Message::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message::id() const {
  // @@protoc_insertion_point(field_get:gen.Message.id)
  return id_.GetNoArena();
}
inline void Message::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gen.Message.id)
}
#if LANG_CXX11
inline void Message::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gen.Message.id)
}
#endif
inline void Message::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gen.Message.id)
}
inline void Message::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gen.Message.id)
}
inline ::std::string* Message::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:gen.Message.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_id() {
  // @@protoc_insertion_point(field_release:gen.Message.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:gen.Message.id)
}

// .gen.key_value_store.Message keyValueStoreMessage = 4;
inline bool Message::has_keyvaluestoremessage() const {
  return messageInternal_case() == kKeyValueStoreMessage;
}
inline void Message::set_has_keyvaluestoremessage() {
  _oneof_case_[0] = kKeyValueStoreMessage;
}
inline void Message::clear_keyvaluestoremessage() {
  if (has_keyvaluestoremessage()) {
    delete messageInternal_.keyvaluestoremessage_;
    clear_has_messageInternal();
  }
}
inline  const ::gen::key_value_store::Message& Message::keyvaluestoremessage() const {
  // @@protoc_insertion_point(field_get:gen.Message.keyValueStoreMessage)
  return has_keyvaluestoremessage()
      ? *messageInternal_.keyvaluestoremessage_
      : ::gen::key_value_store::Message::default_instance();
}
inline ::gen::key_value_store::Message* Message::mutable_keyvaluestoremessage() {
  if (!has_keyvaluestoremessage()) {
    clear_messageInternal();
    set_has_keyvaluestoremessage();
    messageInternal_.keyvaluestoremessage_ = new ::gen::key_value_store::Message;
  }
  // @@protoc_insertion_point(field_mutable:gen.Message.keyValueStoreMessage)
  return messageInternal_.keyvaluestoremessage_;
}
inline ::gen::key_value_store::Message* Message::release_keyvaluestoremessage() {
  // @@protoc_insertion_point(field_release:gen.Message.keyValueStoreMessage)
  if (has_keyvaluestoremessage()) {
    clear_has_messageInternal();
    ::gen::key_value_store::Message* temp = messageInternal_.keyvaluestoremessage_;
    messageInternal_.keyvaluestoremessage_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Message::set_allocated_keyvaluestoremessage(::gen::key_value_store::Message* keyvaluestoremessage) {
  clear_messageInternal();
  if (keyvaluestoremessage) {
    set_has_keyvaluestoremessage();
    messageInternal_.keyvaluestoremessage_ = keyvaluestoremessage;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.Message.keyValueStoreMessage)
}

// .gen.membership_protocol.Message membershipProtocolMessage = 5;
inline bool Message::has_membershipprotocolmessage() const {
  return messageInternal_case() == kMembershipProtocolMessage;
}
inline void Message::set_has_membershipprotocolmessage() {
  _oneof_case_[0] = kMembershipProtocolMessage;
}
inline void Message::clear_membershipprotocolmessage() {
  if (has_membershipprotocolmessage()) {
    delete messageInternal_.membershipprotocolmessage_;
    clear_has_messageInternal();
  }
}
inline  const ::gen::membership_protocol::Message& Message::membershipprotocolmessage() const {
  // @@protoc_insertion_point(field_get:gen.Message.membershipProtocolMessage)
  return has_membershipprotocolmessage()
      ? *messageInternal_.membershipprotocolmessage_
      : ::gen::membership_protocol::Message::default_instance();
}
inline ::gen::membership_protocol::Message* Message::mutable_membershipprotocolmessage() {
  if (!has_membershipprotocolmessage()) {
    clear_messageInternal();
    set_has_membershipprotocolmessage();
    messageInternal_.membershipprotocolmessage_ = new ::gen::membership_protocol::Message;
  }
  // @@protoc_insertion_point(field_mutable:gen.Message.membershipProtocolMessage)
  return messageInternal_.membershipprotocolmessage_;
}
inline ::gen::membership_protocol::Message* Message::release_membershipprotocolmessage() {
  // @@protoc_insertion_point(field_release:gen.Message.membershipProtocolMessage)
  if (has_membershipprotocolmessage()) {
    clear_has_messageInternal();
    ::gen::membership_protocol::Message* temp = messageInternal_.membershipprotocolmessage_;
    messageInternal_.membershipprotocolmessage_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Message::set_allocated_membershipprotocolmessage(::gen::membership_protocol::Message* membershipprotocolmessage) {
  clear_messageInternal();
  if (membershipprotocolmessage) {
    set_has_membershipprotocolmessage();
    messageInternal_.membershipprotocolmessage_ = membershipprotocolmessage;
  }
  // @@protoc_insertion_point(field_set_allocated:gen.Message.membershipProtocolMessage)
}

inline bool Message::has_messageInternal() const {
  return messageInternal_case() != MESSAGEINTERNAL_NOT_SET;
}
inline void Message::clear_has_messageInternal() {
  _oneof_case_[0] = MESSAGEINTERNAL_NOT_SET;
}
inline Message::MessageInternalCase Message::messageInternal_case() const {
  return Message::MessageInternalCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace gen

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WrapperMessage_2eproto__INCLUDED
